Set --fail flag on curl
Signed-off-by: Gabriel Adrian Samfira <gsamfira@cloudbasesolutions.com>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -58,16 +58,19 @@ runs:
       shell: bash
       run: |
         set +e
-        URL=$( curl -s http://127.0.0.1:4040/api/tunnels | jq -r ".tunnels[0].public_url" )
         CNT=0
-        while [ $? -ne 0 ];do
-          URL=$( curl -s http://127.0.0.1:4040/api/tunnels | jq -r ".tunnels[0].public_url" )
-          sleep 1
-          CNT=$(( CNT + 1 ))
-          if [ $CNT -gt 30 ];then
-            echo "Failed to get tunnel URL"
-            exit 1
+        RESULT=$(curl -s --fail http://127.0.0.1:4040/api/tunnels)
+        while [ -z "$RESULT" ];do
+          RESULT=$(curl -s --fail http://127.0.0.1:4040/api/tunnels)
+          if [ $? -ne 0 ];then
+            CNT=$(( CNT + 1 ))
+            if [ $CNT -gt 30 ];then
+                echo "Failed to get tunnel URL"
+                exit 1
+            fi
           fi
+          sleep 1
         done
-        echo $URL
+        URL=$( echo "$RESULT" | jq -r ".tunnels[0].public_url" )
+        echo "::add-mask::$URL"
         echo "tunnel-url=$URL" >> $GITHUB_OUTPUT
